### ISSUE TITLE
Icelandic Localisation Messed Up

### ISSUE THREAD

**Issue by litten8** [C1CK/Beyond-Typus-Cultural-Influence#11]
the loc file says icelandic should be called islensku, but in game it shows up as icelandic. might be because of a mod conflict or something? I've checked though, and the only other mods I had with a reference to icelandic were BT itself and the BT dynamic province naming mod.

**Comment by Illuminati4628** [comment]
I've been looking into this and it's actually gotten to a few more cultures in BT14, Including Russian, Low Saxon, Slovak and (West Slavic) Silesian. I have no clue why this is happening but it's something I'll sort out in a release after the new year. It's not too big of an issue however and doesn't do too much harm.
