### ISSUE TITLE
newest file versions for tatar and uzbek

### ISSUE THREAD

**Issue by Argacyan** [C1CK/Beyond-Typus-Cultural-Influence#17]
[kipchak.txt](https://github.com/C1CK/Beyond-Typus-Cultural-Influence/files/8034359/kipchak.txt)
[karluk.txt](https://github.com/C1CK/Beyond-Typus-Cultural-Influence/files/8034377/karluk.txt)

**Comment by Illuminati4628** [comment]
Impemented
