### ISSUE TITLE
Multiple Greek update-related scripted triggers have errors

### ISSUE THREAD

**Issue by neothiamin** [C1CK/Beyond-Typus-Cultural-Influence#6]
1. The `velgoi_culture_region` scripted trigger has `west_burgundy` as an area requirement when the area's name in code is `west_burgundy_area`.
2. The scripted triggers that ought to be `kefales_culture_region`, `savramata_culture_region`, and `krios_savramata_culture_region` have accented characters in their names which a) are not allowed in scripts and b) may have gotten borked somewhere thanks to encoding changes, so those need to be changed.
3. Not quite an issue with a scripted trigger, but the decision `rhomaio_unification_decision` incorrectly uses the scripted trigger `rhomaio_unification_region`.  The `allow` block ought to be the following:
```
allow = {
	151 = {
		has_province_modifier = byz_city_of_cities
	}
	148 = {
		has_province_modifier = byz_co_capital
	}
	any_owned_province = {
		has_province_modifier = byz_anatolian_restoration
	}
	all_province = {
		OR = {
			AND = {
				rhomaio_unification_region = yes
				culture_group = byzantine
			}
			NOT = {
				rhomaio_unification_region = yes
			}
		}
	}	
}
```
I also suggest a custom_trigger_tooltip for the `all_province` block, because that is going to be hella ugly in the tooltip. Also, do those province modifiers even exist?

**Comment by Illuminati4628** [comment]
I've gone through all of this now, the rewrite for the culture regions should have covered issue 1, issue 2 is done and for 3 the commit b7d420b should have it all fixed up. (Those modifiers are existant but require Byzantine Resurgence to actually aquire, WAD)
